### ISSUE TITLE
Starting demo results in error message "Plugin could not be started"

### ISSUE THREAD

**Issue by klues** [asterics/asterics-camerainput-cameramouse#1]
After starting the project with `ant run`:
* Browser starts with demo-info page
* Error message: "Plugin could not be started. ApplicationLauncher.1"
* see stacktrace at: http://prntscr.com/ie0bvu
* Exception is: `NoSuchMethodError: java.lang.Process.waitFor`

My first thought was that the demo was started with an JRE7, which maybe does not support the Process.waitFor() method, but the environment variable `JAVA_HOME` was set to `C:\Program Files (x86)\Java\jdk1.8.0_152` - so that should be ok?!

**Comment by deinhofer** [comment]
Actually I also think that this is the reason: https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor-long-java.util.concurrent.TimeUnit-

Please check the JRE used when using ant run: Check the first lines of console output to find the information.

**Comment by klues** [comment]
Yes, the problem is that `ant run` uses JRE7. However $JAVA_HOME points to 1.8:
https://prnt.sc/ih7hvy

I think the search mechanism for Java should search for JRE8 and not use JRE7, if JRE8 is needed and actually installed.
